version: "3.9"

services:
  backend:
    build: .
    container_name: bendicion_backend
    command: python node.py
    ports:
      - "7777:7777"
    volumes:
      - dbdata:/data
    restart: always
    networks:
      - bendicion_net

  admin:
    build: .
    container_name: bendicion_admin
    command: python admin_server.py
    ports:
      - "8888:8888"
    volumes:
      - dbdata:/data
    restart: always
    networks:
      - bendicion_net

  web:
    build: .
    container_name: bendicion_web
    command: python web_server.py
    ports:
      - "5000:5000"
    volumes:
      - dbdata:/data
    restart: always
    networks:
      - bendicion_net

volumes:
  dbdata:

networks:
  bendicion_net:
    driver: bridge
