version: "3.9"

services:

  usuarios:
    build: ./usuarios/backend
    container_name: bendicion_usuarios
    command: python login_server.py
    ports:
      - "5001:5001"
    volumes:
      - usuarios_db:/app/db
    restart: always
    networks:
      - bendicion_net

  backend:
    build: ./node/backend
    container_name: bendicion_backend
    command: python node.py
    ports:
      - "7777:7777"
    volumes:
      - backend_db:/app/db
    restart: always
    networks:
      - bendicion_net

  admin:
    build: ./admin/backend
    container_name: bendicion_admin
    command: python admin_server.py
    ports:
      - "8888:8888"
    volumes:
      - admin_db:/app/db
    restart: always
    networks:
      - bendicion_net

  web:
    build: ./web/backend
    container_name: bendicion_web
    command: python web_server.py
    ports:
      - "5000:5000"
    volumes:
      - web_db:/app/db
      - ./templates_web:/app/templates_web
      - ./templates_ADMIN:/app/templates_ADMIN
      - ./templates_KYC:/app/templates_KYC
      - ./templates_staking:/app/templates_staking
      - ./static:/app/static
    restart: always
    networks:
      - bendicion_net

  staking:
    build: ./staking/backend
    container_name: staking_server
    command: python staking_server.py
    ports:
      - "6666:6666"
    volumes:
      - staking_db:/app/db
      - ./templates_staking:/app/templates_staking
    restart: always
    networks:
      - bendicion_net

networks:
  bendicion_net:
    driver: bridge

volumes:
  usuarios_db:
  backend_db:
  admin_db:
  web_db:
  staking_db:
