"""Symmetric encryption helpers backed by cryptography primitives."""

from __future__ import annotations

import base64
import json
import os

from cryptography.fernet import Fernet, InvalidToken
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC


_PBKDF2_ITERATIONS = 390_000


def _derive_key_bytes(password: str, salt: bytes) -> bytes:
    """Derive Fernet-compatible key bytes from password and random salt."""
    if not isinstance(password, str) or not password:
        raise ValueError("password must be a non-empty string")
    if not isinstance(salt, bytes) or len(salt) < 16:
        raise ValueError("salt must be at least 16 bytes")

    kdf = PBKDF2HMAC(
        algorithm=hashes.SHA256(),
        length=32,
        salt=salt,
        iterations=_PBKDF2_ITERATIONS,
    )
    return base64.urlsafe_b64encode(kdf.derive(password.encode("utf-8")))


def derivar_clave(password: str, salt: str) -> str:
    """Derive a deterministic key from password and base64 salt."""
    if not isinstance(salt, str) or not salt:
        raise ValueError("salt must be a non-empty base64 string")

    try:
        salt_bytes = base64.urlsafe_b64decode(salt.encode("ascii"))
    except Exception as exc:
        raise ValueError("salt is not valid base64") from exc

    return _derive_key_bytes(password, salt_bytes).decode("ascii")


def generar_clave_maestra(password: str) -> str:
    """Generate a master-key package containing random salt and derived key."""
    salt = os.urandom(16)
    salt_b64 = base64.urlsafe_b64encode(salt).decode("ascii")
    key = _derive_key_bytes(password, salt).decode("ascii")
    return f"{salt_b64}:{key}"


def encriptar_aes(data: str, clave: str) -> str:
    """Encrypt plaintext using password-derived key and return safe payload."""
    if not isinstance(data, str):
        raise ValueError("data must be a string")

    salt = os.urandom(16)
    key = _derive_key_bytes(clave, salt)
    token = Fernet(key).encrypt(data.encode("utf-8"))

    payload = {
        "salt": base64.urlsafe_b64encode(salt).decode("ascii"),
        "token": token.decode("ascii"),
    }

    return base64.urlsafe_b64encode(json.dumps(payload).encode("utf-8")).decode("ascii")


def desencriptar_aes(data: str, clave: str) -> str:
    """Decrypt payload generated by encriptar_aes."""
    if not isinstance(data, str) or not data:
        raise ValueError("data must be a non-empty string")

    try:
        raw = base64.urlsafe_b64decode(data.encode("ascii"))
        payload = json.loads(raw.decode("utf-8"))

        salt = base64.urlsafe_b64decode(payload["salt"].encode("ascii"))
        token = payload["token"].encode("ascii")

        key = _derive_key_bytes(clave, salt)
        plaintext = Fernet(key).decrypt(token)
        return plaintext.decode("utf-8")
    except InvalidToken as exc:
        raise ValueError("Clave invalida o payload alterado") from exc
    except (KeyError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError("Payload cifrado invalido") from exc
